name: Build package and push

inputs:
  debug:
    description: Sets "NODE_ENV" to "debug".
    required: false
    default: false
  type:
    description: Sets semantic version update type.
    default: patch
    type: choice
    options:
      - major
      - minor
      - patch

runs:
  using: composite

  steps:
    - uses: thaibault/install-npm-package-dependencies-action@main
      with:
        debug: ${{ inputs.debug }}

    - name: Update package.json mentioned version.
      id: version
      run: echo "new=$(bash ./determine-version.sh --format 'v${MAJOR}.${MINOR}.${PATH}${CANDIDATE}' ${{inputs.type || 'patch'}})" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: print
      run: echo '${{steps.version.new}}'
      shell: bash

    #- name: Create git tag for newly create package version.
      #run: git tag "${{outputs.NEW_VERSION}}"
      #shell: bash

    #- name: Update artefacts in git repository.
      #run: git commit --all --message 'Publish new version ${{outputs.NEW_VERSION}}.' && git push --tags && git push
      #shell: bash

    #- name: Publish newly created package.
      #env:
      #  NODE_ENV: ${{ contains(inputs.debug, 'true') && 'debug' || '' }}
      #run: yarn publish
